image: dotstart/go-dep:1.10.3

before_script:
  - apt-get install curl git nodejs npm
  - mkdir -p /go/src/github.com/dotStart /go/src/_/builds
  - cp -r $CI_PROJECT_DIR /go/src/github.com/dotStart/Stockpile
  - ln -s /go/src/github.com/dotStart /go/src/_/builds/dotStart

build:
  stage: build
  script:
    - make
