image: dotstart/go-dep:1.10.3

cache:
  paths:
    - /apt-cache
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in

before_script:
  - apt-get update
  - curl -sL https://deb.nodesource.com/setup_10.x | bash -
  - apt-get install -y curl git nodejs
  - mkdir -p /go/src/github.com/dotStart /go/src/_/builds
  - cp -r $CI_PROJECT_DIR /go/src/github.com/dotStart/Stockpile
  - ln -s /go/src/github.com/dotStart /go/src/_/builds/dotStart

build:
  stage: build
  script:
    - make
