// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// *
// Represents a complete user profile.
type Profile struct {
	Id                   string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string             `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Properties           []*ProfileProperty `protobuf:"bytes,3,rep,name=properties,proto3" json:"properties,omitempty"`
	Textures             *ProfileTextures   `protobuf:"bytes,4,opt,name=textures,proto3" json:"textures,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_7a29ef36c77a3b74, []int{0}
}
func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (dst *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(dst, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

func (m *Profile) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Profile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Profile) GetProperties() []*ProfileProperty {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *Profile) GetTextures() *ProfileTextures {
	if m != nil {
		return m.Textures
	}
	return nil
}

type ProfileProperty struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Signature            string   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileProperty) Reset()         { *m = ProfileProperty{} }
func (m *ProfileProperty) String() string { return proto.CompactTextString(m) }
func (*ProfileProperty) ProtoMessage()    {}
func (*ProfileProperty) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_7a29ef36c77a3b74, []int{1}
}
func (m *ProfileProperty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileProperty.Unmarshal(m, b)
}
func (m *ProfileProperty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileProperty.Marshal(b, m, deterministic)
}
func (dst *ProfileProperty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileProperty.Merge(dst, src)
}
func (m *ProfileProperty) XXX_Size() int {
	return xxx_messageInfo_ProfileProperty.Size(m)
}
func (m *ProfileProperty) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileProperty.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileProperty proto.InternalMessageInfo

func (m *ProfileProperty) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProfileProperty) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *ProfileProperty) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type ProfileTextures struct {
	ProfileId            string   `protobuf:"bytes,1,opt,name=profileId,proto3" json:"profileId,omitempty"`
	ProfileName          string   `protobuf:"bytes,2,opt,name=profileName,proto3" json:"profileName,omitempty"`
	SkinUrl              string   `protobuf:"bytes,3,opt,name=skinUrl,proto3" json:"skinUrl,omitempty"`
	CapeUrl              string   `protobuf:"bytes,4,opt,name=capeUrl,proto3" json:"capeUrl,omitempty"`
	Timestamp            int64    `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileTextures) Reset()         { *m = ProfileTextures{} }
func (m *ProfileTextures) String() string { return proto.CompactTextString(m) }
func (*ProfileTextures) ProtoMessage()    {}
func (*ProfileTextures) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_7a29ef36c77a3b74, []int{2}
}
func (m *ProfileTextures) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileTextures.Unmarshal(m, b)
}
func (m *ProfileTextures) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileTextures.Marshal(b, m, deterministic)
}
func (dst *ProfileTextures) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileTextures.Merge(dst, src)
}
func (m *ProfileTextures) XXX_Size() int {
	return xxx_messageInfo_ProfileTextures.Size(m)
}
func (m *ProfileTextures) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileTextures.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileTextures proto.InternalMessageInfo

func (m *ProfileTextures) GetProfileId() string {
	if m != nil {
		return m.ProfileId
	}
	return ""
}

func (m *ProfileTextures) GetProfileName() string {
	if m != nil {
		return m.ProfileName
	}
	return ""
}

func (m *ProfileTextures) GetSkinUrl() string {
	if m != nil {
		return m.SkinUrl
	}
	return ""
}

func (m *ProfileTextures) GetCapeUrl() string {
	if m != nil {
		return m.CapeUrl
	}
	return ""
}

func (m *ProfileTextures) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterType((*Profile)(nil), "rpc.Profile")
	proto.RegisterType((*ProfileProperty)(nil), "rpc.ProfileProperty")
	proto.RegisterType((*ProfileTextures)(nil), "rpc.ProfileTextures")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_common_7a29ef36c77a3b74) }

var fileDescriptor_common_7a29ef36c77a3b74 = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0xc6, 0xe5, 0x24, 0xa5, 0xf4, 0x8a, 0x40, 0xb2, 0x3a, 0x78, 0x60, 0xb0, 0x32, 0x65, 0xb2,
	0x10, 0xf0, 0x04, 0x6c, 0x2c, 0xa8, 0x8a, 0x60, 0x60, 0x74, 0x13, 0x53, 0xac, 0x26, 0xb1, 0x65,
	0x5f, 0x10, 0x3c, 0x08, 0x4f, 0xc0, 0x8b, 0x22, 0xe7, 0xbf, 0xba, 0xf9, 0xfb, 0x7e, 0x77, 0xdf,
	0x9d, 0xce, 0x70, 0x55, 0x98, 0xba, 0x36, 0x8d, 0xb0, 0xce, 0xa0, 0xa1, 0xb1, 0xb3, 0x45, 0xfa,
	0x4b, 0x60, 0xbd, 0x77, 0xe6, 0x43, 0x57, 0x8a, 0x5e, 0x43, 0xa4, 0x4b, 0x46, 0x38, 0xc9, 0x36,
	0x79, 0xa4, 0x4b, 0x4a, 0x21, 0x69, 0x64, 0xad, 0x58, 0xd4, 0x39, 0xdd, 0x9b, 0x3e, 0x02, 0x58,
	0x67, 0xac, 0x72, 0xa8, 0x95, 0x67, 0x31, 0x8f, 0xb3, 0xed, 0xfd, 0x4e, 0x38, 0x5b, 0x88, 0x21,
	0x65, 0xdf, 0xd3, 0x9f, 0x7c, 0x51, 0x47, 0xef, 0xe0, 0x12, 0xd5, 0x37, 0xb6, 0x4e, 0x79, 0x96,
	0x70, 0x72, 0xde, 0xf3, 0x3a, 0xb0, 0x7c, 0xaa, 0x4a, 0xdf, 0xe1, 0xe6, 0x2c, 0x70, 0x5a, 0x87,
	0x2c, 0xd6, 0xd9, 0xc1, 0xea, 0x4b, 0x56, 0xed, 0xb8, 0x63, 0x2f, 0xe8, 0x2d, 0x6c, 0xbc, 0x3e,
	0x36, 0x32, 0x44, 0xb1, 0xb8, 0x23, 0xb3, 0x91, 0xfe, 0x91, 0x29, 0x7b, 0x1c, 0x1c, 0x3a, 0x6c,
	0x6f, 0x3d, 0x8f, 0x17, 0x98, 0x0d, 0xca, 0x61, 0x3b, 0x88, 0x97, 0xf9, 0x1e, 0x4b, 0x8b, 0x32,
	0x58, 0xfb, 0x93, 0x6e, 0xde, 0x5c, 0x35, 0xcc, 0x1b, 0x65, 0x20, 0x85, 0xb4, 0x2a, 0x90, 0xa4,
	0x27, 0x83, 0x0c, 0x33, 0x51, 0xd7, 0xca, 0xa3, 0xac, 0x2d, 0x5b, 0x71, 0x92, 0xc5, 0xf9, 0x6c,
	0x3c, 0xa5, 0xc0, 0xb5, 0x11, 0x47, 0x8d, 0x9f, 0xed, 0x41, 0x94, 0x06, 0x3d, 0x4a, 0x87, 0xc2,
	0xa3, 0x29, 0x4e, 0x56, 0x57, 0x2a, 0x9c, 0xef, 0x70, 0xd1, 0x7d, 0xe4, 0xc3, 0x7f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xb9, 0x29, 0x12, 0x2a, 0xd8, 0x01, 0x00, 0x00,
}
